version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./keycloak.env

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    env_file: ./keycloak.env
    volumes:
      - ./pet-project-realm-export.json:/tmp/realm.json
    ports:
      - 18080:8080
    depends_on:
      - postgres