server:
  port: 8888

spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: sandbox.smtp.mailtrap.io
    username: e4dafac341bbfc
    password: bd88954c0017df
    port: '2525'
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5434/pet-project
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

keycloak:
  auth-server-url: http://localhost:18080/auth/
  credentials:
    secret: 4eb2285d-7e78-487b-8f07-44b1103f2dd1
  realm: pet-project-realm
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: pet-project-client
