server:
  port: 8888

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-project
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

keycloak:
  auth-server-url: http://localhost:18080/auth/
  credentials:
    secret: 3a00631f-0729-4693-b4f6-8858b7a7e441
  realm: pet-project-realm
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: pet-project-client