server:
  port: 8888

spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: petproject2381@gmail.com
    password: wwxyjknjjbbairyl
    port: '587'
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-project
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

keycloak:
  auth-server-url: http://localhost:18080/auth/
  credentials:
    secret: 'Get new secret key in credentials tab'
  realm: pet-project-realm
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: pet-project-client