version: '3'

volumes:
  postgres_keycloak_data:
    driver: local
  postgres_db_data:
    driver: local

services:
  postgres-keycloak:
    image: postgres
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    env_file: ./keycloak.env

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    env_file: ./keycloak.env
    volumes:
      - ./pet-project-realm-export.json:/tmp/realm.json
    ports:
      - 18080:8080
    depends_on:
      - postgres-keycloak

  postgres-db:
    image: postgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    env_file: ./database.env
    ports:
      - "5434:5432"
